### ISSUE TITLE
only once request, but server will do more than once request.

### ISSUE THREAD

**Issue by docooler** [xluohome/smscode#2]
写的这个工具相当实用，我也学习了下源码。不过看起来只有一次请求，但是手机可能会收到多条信息。
apiserver.go 里面的case api.req[hash] <- req:会不停的给worker发请求。虽然我们只需要一次。我没有运行过这个代码，不过从代码review上来说是会发送多次请求给worker。下面我写了个简单模型：
package main

import (
		"log"
		"time"
		"math/rand"
		)

func  main() {
	ch1 := make(chan int)
	ch2 := make(chan int)

	go func () {
		for a := range ch1 {
			<-time.After(5)
			ch2 <-a
		}
	}()
	d := rand.Intn(100)
	for  {
		select {
		case ch1 <- d:
		case  a := <-ch2:
			log.Println("get a = ", a)
			// return
		case <-time.After(time.Second):
			log.Println("time out 1000")

		}
	}
}

我们运行以后可以看到：
log.Println("get a = ", a)执行了很多遍，说明worker一直在执行这个请求（也就是发送了多条信息）。只是这个代码里面加了return所以只care第一条。我觉得应该把 api.req[hash] <- req放到for循环外。

**Comment by xluohome** [comment]
非常感谢提交pr；

您写的demo 与smscode中的 for select 有相似用法。但smscode中的这个for 循环不会超过2次以上：第一次循环是输入数据到req[hash] chan ,第二次循环是等待 resultchan chan到来或者超时chan 的触发；
且这两个chan 是一对一的，保证了在并发时的安全。 所以不存在您说的会发送多次手机验证码的情况发生（收到多个验证码）。

另为 ，为什么要用这种方式实现，我当时考虑到即要提高并发处理量但又要限制单个手机号的并发量，简单说就是要限制同一个手机号API请求是顺序同步的，这样可以做一些单号码的发送限制；

不知我上面的回复是否对您有帮助？

谢谢；
